name: Deploy Nuxt 3 Static Site

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the Node.js version your Nuxt app uses

      - name: Install dependencies
        run: npm install # Or pnpm install, yarn install based on your package manager

      - name: Build Nuxt application for static generation
        run: npx nuxt generate # This command builds your Nuxt app into static HTML files

      - name: Deploy to GitHub Pages (or other static hosting)
        uses: peaceiris/actions-gh-pages@v3 # Example action for GitHub Pages deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory where Nuxt generates static files (usually 'dist')
          # If deploying to a subfolder on GitHub Pages, uncomment and configure:
          # base_url: /<your-repository-name>/
